/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    services: Service;
    previousWorks: PreviousWork;
    media: Media;
    users: User;
  };
  globals: {
    info: Info;
  };
}
export interface Service {
  id: string;
  name?: string;
  description?: string;
  iconUrl?: string;
  updatedAt: string;
  createdAt: string;
}
export interface PreviousWork {
  id: string;
  service?: string;
  media?: {
    image: string | Media;
    id?: string;
  }[];
  updatedAt: string;
  createdAt: string;
}
export interface Media {
  id: string;
  updatedAt: string;
  createdAt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
}
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  salt?: string;
  hash?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
export interface Info {
  id: string;
  businessName?: string;
  phoneNumber?: string;
  email?: string;
  updatedAt?: string;
  createdAt?: string;
}
